name: Deploy AWS Lambda

on:
  push:
    branches:
      - main

  workflow_dispatch: 
 paths:
      - 'lambda/**''

jobs:
  deploy-lambda: # Name of our job
    runs-on: ubuntu-latest # Sets or specifies the runner
    steps:
    - uses: actions/checkout@v2

    - name: Set Up Python # Sets up our python enviroment
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies # Installs any packages
      run: |
        python -m pip install --upgrade pip
        pip install -r lambda/requirements.txt -t lambda/

    - name: Configure AWS Credentials # Sets up our AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Deploy to AWS Lambda # Zips lambda directory and updates lambda function
      run: |
        cd lambda
        zip -r lambda.zip .
        aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip

    - name: Debug GitHub Actions
      run: |
        echo "Current directory: $(pwd)"
        ls -R
